# Generated by Django 5.1.2 on 2024-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.CharField(max_length=15),
        ),
    ]
