# Generated by Django 5.1.2 on 2024-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_register', '0002_alter_videogame_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.DateField(),
        ),
    ]
